filter:
    paths:
        - src/*
    excluded_paths:
        - tests/*
build:
    environment:
        php:
            version: 8.0.10
            ini:
                'xdebug.mode': 'coverage'
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - command: vendor/bin/phpunit --coverage-clover=coverage.clover
                    - command: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
checks:
    php: true
tools:
    external_code_coverage:
        timeout: 900
